"""refine schema with constraints

Revision ID: 3d063043e759
Revises: ad09c5a444ed
Create Date: 2025-11-21 11:31:02.697180

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d063043e759"
down_revision: Union[str, None] = "ad09c5a444ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ai_logs", "request_text", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "ai_logs", "ai_output_text", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "chat_logs", "user_message", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column("chat_logs", "ai_message", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("episodes", "title", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("episodes", "purpose", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("episodes", "situation", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("episodes", "task", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("episodes", "action", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("episodes", "result", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "life_events", "school_year", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column("life_events", "category", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("life_events", "title", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "rag_embeddings", "source_type", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "rag_embeddings",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=False,
    )
    op.alter_column(
        "rag_embeddings", "content", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column("strengths", "name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("value_axes", "name", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("value_axes", "name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("strengths", "name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("rag_embeddings", "content", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "rag_embeddings",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=True,
    )
    op.alter_column(
        "rag_embeddings", "source_type", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column("life_events", "title", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("life_events", "category", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "life_events", "school_year", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column("episodes", "result", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("episodes", "action", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("episodes", "task", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("episodes", "situation", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("episodes", "purpose", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("episodes", "title", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("chat_logs", "ai_message", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("chat_logs", "user_message", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("ai_logs", "ai_output_text", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("ai_logs", "request_text", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
